#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_Chain_Lantern

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BP_PhysicObject_Chain_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_Chain_Lantern.BP_PhysicObject_Chain_Lantern_C
// 0x0030 (0x03E0 - 0x03B0)
class ABP_PhysicObject_Chain_Lantern_C final : public ABP_PhysicObject_Chain_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PhysicObject_Chain_Lantern_C;    // 0x03B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           EmitColor;                                         // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AttenuationRadius;                                 // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void F_Update();
	void ExecuteUbergraph_BP_PhysicObject_Chain_Lantern(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_Chain_Lantern_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_Chain_Lantern_C")
	}
	static class ABP_PhysicObject_Chain_Lantern_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_Chain_Lantern_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_Chain_Lantern_C;

SDK_NAMESPACE_END
