#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_HangingBone

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_PhysicObject_HangingBone.BP_PhysicObject_HangingBone_C.ExecuteUbergraph_BP_PhysicObject_HangingBone
// 0x0008 (0x0008 - 0x0000)
struct BP_PhysicObject_HangingBone_C_ExecuteUbergraph_BP_PhysicObject_HangingBone final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_PhysicObject_HangingBone_C_ExecuteUbergraph_BP_PhysicObject_HangingBone;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
