#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projector_Pole

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_Projector_Pole.BP_Projector_Pole_C.ExecuteUbergraph_BP_Projector_Pole
// 0x0004 (0x0004 - 0x0000)
struct BP_Projector_Pole_C_ExecuteUbergraph_BP_Projector_Pole final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_Projector_Pole_C_ExecuteUbergraph_BP_Projector_Pole;

// Function BP_Projector_Pole.BP_Projector_Pole_C.F_Update
// 0x0010 (0x0010 - 0x0000)
struct BP_Projector_Pole_C_F_Update final
{
public:
	class ABP_Projector_C*                        K2Node_DynamicCast_AsBP_Projector;                 // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_Projector_Pole_C_F_Update;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
