#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_CactusDeco

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BP_PhysicObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_CactusDeco.BP_PhysicObject_CactusDeco_C
// 0x0018 (0x0370 - 0x0358)
class ABP_PhysicObject_CactusDeco_C final : public ABP_PhysicObject_C
{
public:
	class UPhysicsConstraintComponent*            Chain1;                                            // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAC_WindGusts_C*                        AC_WindGusts;                                      // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRandomStream                          Stream;                                            // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_CactusDeco_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_CactusDeco_C")
	}
	static class ABP_PhysicObject_CactusDeco_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_CactusDeco_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_CactusDeco_C;

SDK_NAMESPACE_END
