#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_Scarecrow

#include "Basic.hpp"

#include "BP_PhysicObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_Scarecrow.BP_PhysicObject_Scarecrow_C
// 0x0018 (0x0370 - 0x0358)
class ABP_PhysicObject_Scarecrow_C final : public ABP_PhysicObject_C
{
public:
	class UPhysicsConstraintComponent*            PhysicsConstraint;                                 // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SceneRoot;                                         // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_Scarecrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_Scarecrow_C")
	}
	static class ABP_PhysicObject_Scarecrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_Scarecrow_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_Scarecrow_C;

SDK_NAMESPACE_END
