#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_HangingBottle_B

#include "Basic.hpp"

#include "BP_PhysicObject_HangingBottle_A_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_HangingBottle_B.BP_PhysicObject_HangingBottle_B_C
// 0x0000 (0x0388 - 0x0388)
class ABP_PhysicObject_HangingBottle_B_C final : public ABP_PhysicObject_HangingBottle_A_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_HangingBottle_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_HangingBottle_B_C")
	}
	static class ABP_PhysicObject_HangingBottle_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_HangingBottle_B_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_HangingBottle_B_C;

SDK_NAMESPACE_END
