#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_SwingDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_PhysicObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_SwingDoor.BP_PhysicObject_SwingDoor_C
// 0x0018 (0x0370 - 0x0358)
class ABP_PhysicObject_SwingDoor_C final : public ABP_PhysicObject_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PhysicObject_SwingDoor_C;        // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPhysicsConstraintComponent*            PhysicsConstraint;                                 // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_Player_C*                           playerInside;                                      // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_PhysicObject_SwingDoor_StaticMesh_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__BP_PhysicObject_SwingDoor_StaticMesh_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void ExecuteUbergraph_BP_PhysicObject_SwingDoor(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_SwingDoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_SwingDoor_C")
	}
	static class ABP_PhysicObject_SwingDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_SwingDoor_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_SwingDoor_C;

SDK_NAMESPACE_END
