#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_Chain_Skull

#include "Basic.hpp"

#include "BP_PhysicObject_Chain_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_Chain_Skull.BP_PhysicObject_Chain_Skull_C
// 0x0000 (0x03B0 - 0x03B0)
class ABP_PhysicObject_Chain_Skull_C final : public ABP_PhysicObject_Chain_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_Chain_Skull_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_Chain_Skull_C")
	}
	static class ABP_PhysicObject_Chain_Skull_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_Chain_Skull_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_Chain_Skull_C;

SDK_NAMESPACE_END
