#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PianoKey_Half

#include "Basic.hpp"

#include "BP_PianoKey_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PianoKey_Half.BP_PianoKey_Half_C
// 0x0000 (0x02F0 - 0x02F0)
class ABP_PianoKey_Half_C final : public ABP_PianoKey_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PianoKey_Half_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PianoKey_Half_C")
	}
	static class ABP_PianoKey_Half_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PianoKey_Half_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PianoKey_Half_C;

SDK_NAMESPACE_END
