#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject_GlassBottleSmall

#include "Basic.hpp"

#include "BP_PhysicObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhysicObject_GlassBottleSmall.BP_PhysicObject_GlassBottleSmall_C
// 0x0000 (0x0358 - 0x0358)
class ABP_PhysicObject_GlassBottleSmall_C final : public ABP_PhysicObject_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_GlassBottleSmall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_GlassBottleSmall_C")
	}
	static class ABP_PhysicObject_GlassBottleSmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_GlassBottleSmall_C>();
	}
};
// DUMPER7_ASSERTS_ABP_PhysicObject_GlassBottleSmall_C;

SDK_NAMESPACE_END
