#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Structure

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Structure.BP_Structure_C
// 0x0008 (0x02B8 - 0x02B0)
class ABP_Structure_C : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Structure_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Structure_C")
	}
	static class ABP_Structure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Structure_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Structure_C;

SDK_NAMESPACE_END
