#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpellProjectile_Cactus_Decoy

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_SpellProjectile_Cactus_Decoy.BP_SpellProjectile_Cactus_Decoy_C.ExecuteUbergraph_BP_SpellProjectile_Cactus_Decoy
// 0x0004 (0x0004 - 0x0000)
struct BP_SpellProjectile_Cactus_Decoy_C_ExecuteUbergraph_BP_SpellProjectile_Cactus_Decoy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_SpellProjectile_Cactus_Decoy_C_ExecuteUbergraph_BP_SpellProjectile_Cactus_Decoy;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
