#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tweak_Epic_HeadshotConfettis

#include "Basic.hpp"

#include "BP_Tweak_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Tweak_Epic_HeadshotConfettis.BP_Tweak_Epic_HeadshotConfettis_C
// 0x0000 (0x0328 - 0x0328)
class ABP_Tweak_Epic_HeadshotConfettis_C final : public ABP_Tweak_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Tweak_Epic_HeadshotConfettis_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Tweak_Epic_HeadshotConfettis_C")
	}
	static class ABP_Tweak_Epic_HeadshotConfettis_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Tweak_Epic_HeadshotConfettis_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Tweak_Epic_HeadshotConfettis_C;

SDK_NAMESPACE_END
