#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TalkingCharacter_Grave

#include "Basic.hpp"

#include "BP_TalkingCharacter_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TalkingCharacter_Grave.BP_TalkingCharacter_Grave_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_TalkingCharacter_Grave_C final : public ABP_TalkingCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TalkingCharacter_Grave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TalkingCharacter_Grave_C")
	}
	static class ABP_TalkingCharacter_Grave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TalkingCharacter_Grave_C>();
	}
};
// DUMPER7_ASSERTS_ABP_TalkingCharacter_Grave_C;

SDK_NAMESPACE_END
