#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_ChallengeCategory

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_ChallengeCategory.E_ChallengeCategory
// NumValues: 0x0007
enum class E_ChallengeCategory : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	E_MAX                                    = 6,
};

SDK_NAMESPACE_END
