#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: L_CactusDay2026_Lobby

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass L_CactusDay2026_Lobby.L_CactusDay2026_Lobby_C
// 0x0000 (0x02B8 - 0x02B8)
class AL_CactusDay2026_Lobby_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("L_CactusDay2026_Lobby_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"L_CactusDay2026_Lobby_C")
	}
	static class AL_CactusDay2026_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AL_CactusDay2026_Lobby_C>();
	}
};
// DUMPER7_ASSERTS_AL_CactusDay2026_Lobby_C;

SDK_NAMESPACE_END
