#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_DartPlayerValues

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_DartPlayerValues.ST_DartPlayerValues
// 0x0010 (0x0010 - 0x0000)
struct FST_DartPlayerValues final
{
public:
	class APlayerState*                           PlayerState_10_AAA59C0448291B0FE04C3AA2403E2683;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	int32                                         PlayerScore_12_26FA674047225A8C9779A8A0799DA4C8;   // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_FST_DartPlayerValues;

SDK_NAMESPACE_END
