#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Cow

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ABP_Cow_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Cow.ABP_Cow_C
// 0x00D0 (0x04C0 - 0x03F0)
class UABP_Cow_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3E8[0x8];                                      // 0x03E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct ABP_Cow::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                      // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03F8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0400(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0408(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x0428(0x0070)()
	struct FVector                                K2Node_PropertyAccess;                             // 0x0498(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Speed;                                             // 0x04B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintThreadSafeUpdateAnimation(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Cow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Cow_C")
	}
	static class UABP_Cow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Cow_C>();
	}
};
// DUMPER7_ASSERTS_UABP_Cow_C;

SDK_NAMESPACE_END
