#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Animal_Cow

#include "Basic.hpp"

#include "BP_Animal_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Animal_Cow.BP_Animal_Cow_C
// 0x0000 (0x06E0 - 0x06E0)
class ABP_Animal_Cow_C final : public ABP_Animal_C
{
public:
	uint8                                         Pad_6D3[0x5];                                      // 0x06D3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UBoxComponent*                          Box;                                               // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Animal_Cow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Animal_Cow_C")
	}
	static class ABP_Animal_Cow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Animal_Cow_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Animal_Cow_C;

SDK_NAMESPACE_END
