#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Animal_Hen

#include "Basic.hpp"

#include "BP_Animal_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Animal_Hen.BP_Animal_Hen_C
// 0x0000 (0x06E0 - 0x06E0)
class ABP_Animal_Hen_C final : public ABP_Animal_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Animal_Hen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Animal_Hen_C")
	}
	static class ABP_Animal_Hen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Animal_Hen_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Animal_Hen_C;

SDK_NAMESPACE_END
