#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlendableAtmosphere_CactusDay

#include "Basic.hpp"

#include "BP_BlendableAtmosphere_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BlendableAtmosphere_CactusDay.BP_BlendableAtmosphere_CactusDay_C
// 0x0000 (0x04D8 - 0x04D8)
class ABP_BlendableAtmosphere_CactusDay_C final : public ABP_BlendableAtmosphere_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BlendableAtmosphere_CactusDay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BlendableAtmosphere_CactusDay_C")
	}
	static class ABP_BlendableAtmosphere_CactusDay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BlendableAtmosphere_CactusDay_C>();
	}
};
// DUMPER7_ASSERTS_ABP_BlendableAtmosphere_CactusDay_C;

SDK_NAMESPACE_END
