#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cart

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "E_DamageCategory_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Cart.BP_Cart_C
// 0x00C8 (0x0378 - 0x02B0)
class ABP_Cart_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara1;                                          // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight1;                                        // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        S_RailCart;                                        // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Socke_SmoothTransform;                             // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_Rails_C*                            rails;                                             // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	double                                        currentDistance;                                   // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Speed;                                             // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          tickEnabledDirty;                                  // 0x031C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31D[0x3];                                      // 0x031D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                oldCartRot;                                        // 0x0320(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        cartLocalVelocity;                                 // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                oldActorLoc;                                       // 0x0340(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         hitActors;                                         // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class ALandscape*                             LandscapeActor;                                    // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          goRightOrLeft;                                     // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_Cart_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__BP_Cart_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void ExecuteUbergraph_BP_Cart(int32 EntryPoint);
	void F_Activate(int32 Wildcard, double Delay, class AActor* Owner_0);
	void F_Activate_Location(const struct FVector& Location, class AActor* Owner_0, int32 Wildcard, class UPrimitiveComponent* Component);
	void F_AddImpulseServer(const struct FVector& HitNormal, const struct FVector& Location);
	void F_Bounce(const struct FVector& DirectionAxis, const struct FVector& BounceLoc);
	void F_BuffManagerClearBuffFromActor(class UClass* Buff);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_Channel(class AActor* ChannelingOwner, int32 Wildcard);
	void F_Collisions(bool Direction, bool* Collided, class AActor** HitActor);
	void F_DamageEnemies(bool* Hit);
	void F_DamageFeedback(const struct FHitResult& Hit, class AActor* Owner_0, double Damages, class UClass* DamageType, bool Critical, E_DamageCategory Element, class FName ItemName);
	void F_EnableTickTemporary();
	void F_EventAlert();
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	void F_HoverInteract();
	void F_Interact(class AActor* Owner_0, int32 Wildcard);
	void F_KillCombo();
	void F_MoveActorAlongSpline();
	void F_Particles();
	void F_PassWildcard(int32 Wildcard);
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void F_QuestProgress(class FName Tag);
	void F_ReceiveBuff(class AActor* Owner_0, const struct FVector& ReceivedLoc, class UClass* BuffObject);
	void F_RemoveBuff(class UClass* BuffObject);
	void F_RemoveNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_SendUnlockables(const TArray<class UClass*>& Unlockables);
	void F_ServerDamages(double Damages, class UClass* DamageType, class AActor* Causer, E_DamageCategory Element, class FName ItemName);
	void F_ServerExplosion(class FName ExplosionName, double Damages, class AActor* Causer);
	void F_SetAttachedActor(class AActor* AttachedActor);
	void F_SetCanBeDestroyedIfNoPlayerAround();
	void F_SetCustomMaterialParameter(class FName Param, double Value);
	void F_SmoothCart();
	void F_SnapToRails(double Distance);
	void F_Sound();
	void F_SpawnNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_StartInteract(class AActor* Owner_0);
	void F_StartPhysic(class UPrimitiveComponent* Component, const struct FVector& HitLoc, const struct FVector& Normal, double Strenght, class AActor* hitOwner, E_DamageCategory DamageCategory);
	void F_StopChannel(class AActor* ChannelingActor);
	void F_StopInteract(class AActor* Owner_0);
	void F_TriggerTalisman(class ABP_Item_C* Item, class AActor* WildClassActor);
	void OnRep_tickEnabledDirty();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Cart_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Cart_C")
	}
	static class ABP_Cart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cart_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Cart_C;

SDK_NAMESPACE_END
