#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Enemy_Cryptic_Grunt_Lobby

#include "Basic.hpp"

#include "BP_Enemy_Cryptic_Grunt_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Enemy_Cryptic_Grunt_Lobby.BP_Enemy_Cryptic_Grunt_Lobby_C
// 0x0000 (0x08F0 - 0x08F0)
class ABP_Enemy_Cryptic_Grunt_Lobby_C final : public ABP_Enemy_Cryptic_Grunt_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Enemy_Cryptic_Grunt_Lobby_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Enemy_Cryptic_Grunt_Lobby_C")
	}
	static class ABP_Enemy_Cryptic_Grunt_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Enemy_Cryptic_Grunt_Lobby_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Enemy_Cryptic_Grunt_Lobby_C;

SDK_NAMESPACE_END
