#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Dart

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Item_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Item_Dart.BP_Item_Dart_C
// 0x0040 (0x04F0 - 0x04B0)
class ABP_Item_Dart_C final : public ABP_Item_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Item_Dart_C;                     // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   SM_Dart;                                           // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          canShoot;                                          // 0x04C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsShooting;                                        // 0x04C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C2[0x6];                                      // 0x04C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_DartPower_C*                        UI_DartPower;                                      // 0x04C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        Power;                                             // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DartMinimumDistanceToScorePoints;                  // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CamShakeForce;                                     // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Dartboard_C*                        RefDartboard;                                      // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Item_Dart(int32 EntryPoint);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_Child_Shoot();
	void F_Child_StopShoot();
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	bool F_IsInShootZone();
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void OnBlendOut_12E3BEA7413FB8C0609ADDA762D1548F(class FName NotifyName);
	void OnBlendOut_D5FE6921421ADA39598C25BBAD8C0215(class FName NotifyName);
	void OnCompleted_12E3BEA7413FB8C0609ADDA762D1548F(class FName NotifyName);
	void OnCompleted_D5FE6921421ADA39598C25BBAD8C0215(class FName NotifyName);
	void OnInterrupted_12E3BEA7413FB8C0609ADDA762D1548F(class FName NotifyName);
	void OnInterrupted_D5FE6921421ADA39598C25BBAD8C0215(class FName NotifyName);
	void OnNotifyBegin_12E3BEA7413FB8C0609ADDA762D1548F(class FName NotifyName);
	void OnNotifyBegin_D5FE6921421ADA39598C25BBAD8C0215(class FName NotifyName);
	void OnNotifyEnd_12E3BEA7413FB8C0609ADDA762D1548F(class FName NotifyName);
	void OnNotifyEnd_D5FE6921421ADA39598C25BBAD8C0215(class FName NotifyName);
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Item_Dart_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Item_Dart_C")
	}
	static class ABP_Item_Dart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Item_Dart_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Item_Dart_C;

SDK_NAMESPACE_END
