#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Nitro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Item_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Item_Nitro.BP_Item_Nitro_C
// 0x0040 (0x04F0 - 0x04B0)
class ABP_Item_Nitro_C final : public ABP_Item_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Item_Nitro_C;                    // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sphere;                                            // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Dynamite_Fuse__loop_;                              // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DynamiteTubes;                                  // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          isLit;                                             // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Item_Nitro(int32 EntryPoint);
	void OnBlendOut_C18483AF4363EB776EB07C9EA0D91A18(class FName NotifyName);
	void OnCompleted_C18483AF4363EB776EB07C9EA0D91A18(class FName NotifyName);
	void OnInterrupted_C18483AF4363EB776EB07C9EA0D91A18(class FName NotifyName);
	void OnNotifyBegin_C18483AF4363EB776EB07C9EA0D91A18(class FName NotifyName);
	void OnNotifyEnd_C18483AF4363EB776EB07C9EA0D91A18(class FName NotifyName);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Item_Nitro_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Item_Nitro_C")
	}
	static class ABP_Item_Nitro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Item_Nitro_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Item_Nitro_C;

SDK_NAMESPACE_END
