#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyFireworkSpawner

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_LobbyFireworkSpawner.BP_LobbyFireworkSpawner_C.ExecuteUbergraph_BP_LobbyFireworkSpawner
// 0x0004 (0x0004 - 0x0000)
struct BP_LobbyFireworkSpawner_C_ExecuteUbergraph_BP_LobbyFireworkSpawner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_LobbyFireworkSpawner_C_ExecuteUbergraph_BP_LobbyFireworkSpawner;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
