#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyenemySpawner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LobbyenemySpawner.BP_LobbyenemySpawner_C
// 0x0030 (0x02E0 - 0x02B0)
class ABP_LobbyenemySpawner_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FVector>                        Locations;                                         // 0x02C0(0x0010)(Edit, BlueprintVisible)
	TArray<class UClass*>                         enemies;                                           // 0x02D0(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BP_LobbyenemySpawner(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LobbyenemySpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LobbyenemySpawner_C")
	}
	static class ABP_LobbyenemySpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LobbyenemySpawner_C>();
	}
};
// DUMPER7_ASSERTS_ABP_LobbyenemySpawner_C;

SDK_NAMESPACE_END
