#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyProjector

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LobbyProjector.BP_LobbyProjector_C
// 0x0010 (0x02C0 - 0x02B0)
class ABP_LobbyProjector_C final : public AActor
{
public:
	class UWidgetComponent*                       Widget;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LobbyProjector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LobbyProjector_C")
	}
	static class ABP_LobbyProjector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LobbyProjector_C>();
	}
};
// DUMPER7_ASSERTS_ABP_LobbyProjector_C;

SDK_NAMESPACE_END
