#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Manager_RewardNotifications

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Manager_RewardNotifications.BP_Manager_RewardNotifications_C
// 0x0020 (0x02D0 - 0x02B0)
class ABP_Manager_RewardNotifications_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUI_Rewards_C*                          rewardUi;                                          // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          anyMenuOpenBefore;                                 // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Manager_RewardNotifications(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Manager_RewardNotifications_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Manager_RewardNotifications_C")
	}
	static class ABP_Manager_RewardNotifications_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Manager_RewardNotifications_C>();
	}
};
// DUMPER7_ASSERTS_ABP_Manager_RewardNotifications_C;

SDK_NAMESPACE_END
