#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Villager

#include "Basic.hpp"

#include "BP_NPC_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_NPC_Villager.BP_NPC_Villager_C
// 0x0000 (0x0790 - 0x0790)
#pragma pack(push, 0x1)
class SDK_ALIGN(0x10) ABP_NPC_Villager_C : public ABP_NPC_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Villager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Villager_C")
	}
	static class ABP_NPC_Villager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Villager_C>();
	}
};
#pragma pack(pop)
// DUMPER7_ASSERTS_ABP_NPC_Villager_C;

SDK_NAMESPACE_END
