#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Villager_Leaning

#include "Basic.hpp"

#include "BP_NPC_Villager_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_NPC_Villager_Leaning.BP_NPC_Villager_Leaning_C
// 0x0000 (0x0790 - 0x0790)
class ABP_NPC_Villager_Leaning_C : public ABP_NPC_Villager_C
{
public:
	uint8                                         Pad_781[0x7];                                      // 0x0781(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0788(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Villager_Leaning_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Villager_Leaning_C")
	}
	static class ABP_NPC_Villager_Leaning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Villager_Leaning_C>();
	}
};
// DUMPER7_ASSERTS_ABP_NPC_Villager_Leaning_C;

SDK_NAMESPACE_END
