#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Villager_Leaning_Ghost

#include "Basic.hpp"

#include "BP_NPC_Villager_Leaning_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_NPC_Villager_Leaning_Ghost.BP_NPC_Villager_Leaning_Ghost_C
// 0x0010 (0x07A0 - 0x0790)
class ABP_NPC_Villager_Leaning_Ghost_C final : public ABP_NPC_Villager_Leaning_C
{
public:
	class UNiagaraComponent*                      NS_Skeletal_Ghost;                                 // 0x0790(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Villager_Leaning_Ghost_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Villager_Leaning_Ghost_C")
	}
	static class ABP_NPC_Villager_Leaning_Ghost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Villager_Leaning_Ghost_C>();
	}
};
// DUMPER7_ASSERTS_ABP_NPC_Villager_Leaning_Ghost_C;

SDK_NAMESPACE_END
