#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Hunter_Shop

#include "Basic.hpp"

#include "BP_NPC_Villager_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_NPC_Hunter_Shop.BP_NPC_Hunter_Shop_C
// 0x0010 (0x07A0 - 0x0790)
class ABP_NPC_Hunter_Shop_C final : public ABP_NPC_Villager_C
{
public:
	uint8                                         Pad_781[0x7];                                      // 0x0781(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   SM_CrypticSkull;                                   // 0x0788(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Knife;                                          // 0x0790(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Hunter_Shop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Hunter_Shop_C")
	}
	static class ABP_NPC_Hunter_Shop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Hunter_Shop_C>();
	}
};
// DUMPER7_ASSERTS_ABP_NPC_Hunter_Shop_C;

SDK_NAMESPACE_END
