#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DartGame_Scoreboard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ST_DartPlayerValues_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_DartGame_Scoreboard.UI_DartGame_Scoreboard_C
// 0x0050 (0x0378 - 0x0328)
class UUI_DartGame_Scoreboard_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           VB_AllPlayerScores;                                // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Text;                                    // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             T_DartLeaderboard;                                 // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_19;                                    // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Color;                                      // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Open;                                            // 0x0358(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxPlayerInLeaderboard;                            // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_364[0x4];                                      // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FST_DartPlayerValues>           Player_Score;                                      // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Construct();
	void ExecuteUbergraph_UI_DartGame_Scoreboard(int32 EntryPoint);
	void F_SortPoints(TArray<struct FST_DartPlayerValues>& playerScore);
	void F_UpdatePlayerScores(const TArray<struct FST_DartPlayerValues>& playerScore, const class APlayerState* SelfPlayerState);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_DartGame_Scoreboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_DartGame_Scoreboard_C")
	}
	static class UUI_DartGame_Scoreboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DartGame_Scoreboard_C>();
	}
};
// DUMPER7_ASSERTS_UUI_DartGame_Scoreboard_C;

SDK_NAMESPACE_END
